Repository kvoli/fun-with-friends, pull requests merged in 2019-08, with the labels that each got.

#4 Setup a basic react client with an express server
  .gitignore
  README.md
  client/.gitignore
  client/README.md
  client/package-lock.json
  client/package.json
  client/public/favicon.ico
  client/public/index.html
  client/public/manifest.json
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/index.css
  client/src/index.js
  client/src/logo.svg
  client/src/serviceWorker.js
  package-lock.json
  package.json
  server/.gitignore
  server/package-lock.json
  server/package.json
  server/server.js
Labels: enhancement

#8 Add travis.yml
  .travis.yml
Labels: enhancement

#13 Update README.md badges
  README.md
Labels: documentation

#15 Update .travis.yml to intergrate DockerHUB
  .travis.yml
  README.md
Labels: documentation, enhancement

#23 Ben - Added development mode alongside the previous production mode
  Dockerfile
  README.md
  client/package.json
  server/package.json
  server/server.js
Labels: documentation, enhancement

#26 Ben - Update Readme with Updated Docker Commands
  README.md
Labels: documentation

#28 Ben - Readme Visual Update and New Badge
  README.md
  github-banner.png
Labels: documentation, enhancement

#30 Add tagging to Travis
  .travis.yml
  Dockerfile
  server/package-lock.json
  server/package.json
Labels: bug, enhancement

#31 Optimize build pipeline
  .travis.yml
  Dockerfile
  server/package-lock.json
Labels: enhancement

#32 Add dev script to server's package.json
  server/package.json
Labels: bug

#35 Setup database and added schemas for accounts and artifacts
  .gitignore
  server/models/account.js
  server/models/artifact.js
  server/models/db.js
  server/package-lock.json
  server/package.json
  server/server.js
Labels: documentation, enhancement

#36 Add React main page interface, displaying artifacts in grid
  .travis.yml
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/App.css
  client/src/App.js
  client/src/App.test.js
  client/src/index.js
  client/src/js/components/App.jsx
  client/src/js/components/ArtifactGrid.jsx
  client/src/js/components/ArtifactGridItem.jsx
  client/src/js/components/MainPage.jsx
  client/src/js/components/NavBar.js
  client/src/logo.svg
  client/src/serviceWorker.js
Labels: enhancement

#39 Add user routes and controllers
  server/controllers/user.js
  server/middleware/auth.js
  server/models/account.js
  server/models/db.js
  server/models/user.js
  server/package-lock.json
  server/package.json
  server/routes/routes.js
  server/routes/user.js
  server/server.js
Labels: bug, enhancement

#41 Add react-redux package and skeleton code
  client/package-lock.json
  client/package.json
  client/public/index.html
  client/src/index.js
  client/src/js/actions/index.js
  client/src/js/components/Artifact.jsx
  client/src/js/components/NavBar.js
  client/src/js/constants/action-types.js
  client/src/js/index.js
  client/src/js/reducers/index.js
  client/src/js/store/index.js
  server/controllers/image.js
  server/routes/image.js
  server/routes/routes.js
  server/server.js
Labels: bug, enhancement

#40 Add image route and controller to upload images to cloundinary
  server/controllers/image.js
  server/routes/image.js
  server/routes/routes.js
  server/server.js
Labels: bug, enhancement

#43 Ben Bugfixes
  .eslintrc.json
  server/config.js
  server/controllers/image.js
  server/package-lock.json
  server/package.json
  server/routes/image.js
Labels: bug, documentation

#44 Ben - Fix exports in image controller
  server/controllers/image.js
Labels: bug

#47 update redux | modals | spacing
  client/src/js/actions/index.js
  client/src/js/components/ArtifactDetailed.jsx
  client/src/js/components/ArtifactGrid.jsx
  client/src/js/components/ArtifactModal.jsx
  client/src/js/components/DeleteConfirmation.jsx
  client/src/js/components/MainPage.jsx
  client/src/js/components/NavBar.jsx
  client/src/js/components/artifactData.js
  client/src/js/constants/action-types.js
  client/src/js/index.js
  client/src/js/reducers/artifacts.js
  client/src/js/reducers/focusView.js
  client/src/js/reducers/index.js
  client/src/js/store/index.js
Labels: documentation, enhancement

#48 add local state delete functionality
  client/src/js/components/ArtifactDetailed.jsx
  client/src/js/components/ArtifactForm.jsx
  client/src/js/components/ArtifactModal.jsx
  client/src/js/components/DeleteConfirmation.jsx
  client/src/js/components/DeletePopup.jsx
  client/src/js/components/LoadingCircle.jsx
  client/src/js/components/NavBar.jsx
  client/src/js/reducers/artifacts.js
Labels: Bug Fix, Refactor

#49 add search function for artifact filtering
  client/package-lock.json
  client/package.json
  client/src/js/actions/index.js
  client/src/js/components/ArtifactGrid.jsx
  client/src/js/components/SearchBar.jsx
  client/src/js/constants/action-types.js
  client/src/js/reducers/artifacts.js
  client/src/js/reducers/filters.js
  client/src/js/reducers/focusView.js
  client/src/js/reducers/index.js
  client/src/js/selectors/index.js
Labels: enhancement

#50 Ben - Small API Refactor
  server/config.js
  server/controllers/user.js
  server/middleware/auth.js
  server/models/db.js
  server/models/user.js
  server/package.json
  server/routes/user.js
  server/server.js
Labels: Bug Fix, Refactor

#52 Move dotEnv to production dependency following refactor of API
  server/package-lock.json
  server/package.json
Labels: Bug Fix

#53 Ben - Client Login
  client/package-lock.json
  client/package.json
  client/src/history.js
  client/src/index.js
  client/src/js/actions/auth.js
  client/src/js/components/App.jsx
  client/src/js/components/Login.jsx
  client/src/js/components/Main.jsx
  client/src/js/components/NavBar.jsx
  client/src/js/components/NavProfile.jsx
  client/src/js/components/NavProfileMenu.jsx
  client/src/js/constants/auth.js
  client/src/js/helpers/mock.js
  client/src/js/index.js
  client/src/js/reducers/auth.js
  client/src/js/reducers/index.js
  client/src/js/selectors/auth.js
  client/src/js/selectors/index.js
  client/src/js/store/index.js
Labels: Enhancement

#55 Ben - Artifact API
  server/controllers/artifact.js
  server/controllers/image.js
  server/controllers/user.js
  server/middleware/upload.js
  server/models/artifact.js
  server/models/user.js
  server/package-lock.json
  server/package.json
  server/routes/artifact.js
  server/routes/image.js
  server/routes/routes.js
  server/server.js
Labels: Enhancement, Refactor

#56 Austen/Ben - CRUD functionality on client | UI tidy up | Login required to see images
  client/package-lock.json
  client/package.json
  client/src/js/actions/artifact.js
  client/src/js/actions/auth.js
  client/src/js/actions/index.js
  client/src/js/components/App.jsx
  client/src/js/components/ArtifactDetailed.jsx
  client/src/js/components/ArtifactForm.jsx
  client/src/js/components/ArtifactFormModal.jsx
  client/src/js/components/ArtifactGrid.jsx
  client/src/js/components/ArtifactModal.jsx
  client/src/js/components/DeletePopup.jsx
  client/src/js/components/Login.jsx
  client/src/js/components/Main.jsx
  client/src/js/components/MainPage.jsx
  client/src/js/components/NavBar/LoginButton.jsx
  client/src/js/components/NavBar/NavBar.jsx
  client/src/js/components/NavBar/NavProfile.jsx
  client/src/js/components/NavBar/SignupButton.jsx
  client/src/js/components/NavBar/UserTitle.jsx
  client/src/js/components/NavProfileMenu.jsx
  client/src/js/components/SignUp.jsx
  client/src/js/components/UtilityBar.jsx
  client/src/js/components/artifactData.js
  client/src/js/constants/action-types.js
  client/src/js/constants/artifact.js
  client/src/js/reducers/artifacts.js
  client/src/js/reducers/filters.js
  client/src/js/reducers/focusView.js
  client/src/js/selectors/auth.js
  server/controllers/artifact.js
  server/controllers/image.js
  server/models/artifact.js
  server/package-lock.json
  server/routes/artifact.js
Labels: Bug Fix, Enhancement, bug, invalid

#58 Kvoli branchmerge
  client/src/js/actions/index.js
  client/src/js/actions/snackbar.js
  client/src/js/components/ArtifactForm.jsx
  client/src/js/components/ArtifactGrid.jsx
  client/src/js/components/DeletePopup.jsx
  client/src/js/components/MainPage.jsx
  client/src/js/components/SnackBar.jsx
  client/src/js/constants/action-types.js
  client/src/js/reducers/index.js
  client/src/js/reducers/snackbar.js
  server/package-lock.json
Labels: Bug Fix, Enhancement

#59 Change /api/image/upload to return a https src
  client/src/js/components/ArtifactGrid.jsx
  server/controllers/image.js
  server/package-lock.json
  server/package.json
Labels: Bug Fix, Enhancement

#60 Added refresh button and removed non-functional delete button.
  client/src/js/components/UtilityBar.jsx
Labels: Enhancement, Refactor
