Repository kvoli/fun-with-friends, pull requests merged in 2019-10, with the labels that each got.

#96 Landing Page Improvements
  .gitignore
  client/package-lock.json
  client/package.json
  client/src/SVG/Network.svg
  client/src/SVG/SVGImages.js
  client/src/SVG/communityLogo.svg
  client/src/SVG/downloadLogo.svg
  client/src/SVG/imageLogo.svg
  client/src/SVG/intersection.svg
  client/src/SVG/shareLogo.svg
  client/src/VIDEO/VIDEOFiles.js
  client/src/VIDEO/network.mp4
  client/src/js/components/LandingAnimatedBackground.jsx
  client/src/js/components/LandingPage.jsx
Labels: Bug Fix, Enhancement

#101 Fix middleware to support testing and deployment
  server/middleware/auth.js
Labels: Bug Fix

#107 update landing page, add 404, remove relations and chat
  client/src/SVG/404.svg
  client/src/SVG/SVGImages.js
  client/src/js/actions/artifact.js
  client/src/js/actions/circle.js
  client/src/js/components/AddCircle.jsx
  client/src/js/components/App.jsx
  client/src/js/components/ArtifactDetailed.jsx
  client/src/js/components/ArtifactForm.jsx
  client/src/js/components/Footer.jsx
  client/src/js/components/FourOFour.jsx
  client/src/js/components/GroupPage.jsx
  client/src/js/components/LandingPage.jsx
  client/src/js/components/Main.jsx
  client/src/js/components/Map.jsx
  client/src/js/components/NavBar/NavBar.jsx
  package-lock.json
  package.json
  server/controllers/chat.js
Labels: Bug Fix, Enhancement, Refactor

#108 Fix create circle form add member not working
  client/src/js/components/AddCircle.jsx
Labels: Bug Fix

#129 Fix Bug
  client/src/js/components/UserPage.jsx
Labels: Bug Fix

#130 made change such that the edit artifact and create artifact API send …
  server/controllers/artifact.js
Labels: Bug, Bug Fix

#128 Circle Controller Tests and Refactor
  server/controllers/circle.js
  server/models/user.js
  server/tests/circle.controller.test.js
  server/tests/constants/circles.js
  server/tests/constants/users.js
Labels: Refactor, Testing
