Repository kvoli/fun-with-friends, pull requests merged in 2019-09, with the labels that each got.

#64 Improve project development environment.
  .eslintignore
  .eslintrc.json
  .prettierignore
  .prettierrc
  .travis.yml
  client/.babelrc
  client/README.md
  client/package-lock.json
  client/package.json
  client/src/js/__tests__/app.test.jsx
  client/src/js/__tests__/components/artifactdetailed.test.jsx
  client/src/js/__tests__/components/copyright.test.jsx
  client/src/js/__tests__/components/footer.test.jsx
  client/src/js/__tests__/components/login.test.jsx
  client/src/js/__tests__/components/mainpage.test.jsx
  client/src/js/__tests__/components/navbar.test.jsx
  client/src/js/components/ArtifactDetailed.jsx
  client/src/js/components/SnackBar.jsx
  client/src/setupTests.js
  package-lock.json
  package.json
  server/package-lock.json
  server/package.json
Labels: Bug Fix

#71 Update package-lock
  server/package-lock.json
  server/package.json
Labels: Bug Fix

#76 Ben artifact perms
  .prettierrc
  client/src/js/actions/artifact.js
  client/src/js/components/ArtifactForm.jsx
  client/src/js/components/DeletePopup.jsx
  client/src/js/components/Main.jsx
  client/src/js/components/UtilityBar.jsx
  server/controllers/artifact.js
  server/controllers/circle.js
  server/models/db.js
  server/routes/artifact.js
Labels: Enhancement

#87 Ben test controllers
  .travis.yml
  server/jest.config.js
  server/models/user.js
  server/package-lock.json
  server/package.json
  server/test/artifact_test.js
  server/test/user_test.js
  server/tests/user.controller.test.js
Labels: Testing

#86 update darkmode capabilities
  client/src/js/__tests__/components/navbar.test.jsx
  client/src/js/actions/artifact.js
  client/src/js/actions/index.js
  client/src/js/components/App.jsx
  client/src/js/components/Footer.jsx
  client/src/js/components/NavBar/NavBar.jsx
  client/src/js/constants/action-types.js
  client/src/js/reducers/focusView.js
Labels: Enhancement, Testing

#90 Ben circle bugfixes
  client/src/js/actions/artifact.js
  client/src/js/actions/auth.js
  client/src/js/actions/circle.js
  client/src/js/actions/index.js
  client/src/js/components/AddCircle.jsx
  client/src/js/components/AddCircleMembers.jsx
  client/src/js/components/AddCircleModal.jsx
  client/src/js/components/AddMember.jsx
  client/src/js/components/ArtifactForm.jsx
  client/src/js/components/ArtifactGrid.jsx
  client/src/js/components/CircleArtifactsFeed.jsx
  client/src/js/components/CirclePage/AdminAvatar.jsx
  client/src/js/components/DeleteCircle.jsx
  client/src/js/components/GroupFilterMenu.jsx
  client/src/js/components/GroupPage.jsx
  client/src/js/components/Main.jsx
  client/src/js/constants/action-types.js
  client/src/js/constants/circle.js
  client/src/js/reducers/circle.js
  client/src/js/reducers/filters.js
  client/src/js/selectors/index.js
  server/controllers/artifact.js
  server/controllers/circle.js
  server/models/db.js
  server/routes/circle.js
Labels: Bug Fix, Enhancement
